name: dynamic_content
description: Dynamically update assets from remote sources
version: 0.0.3

environment:
  sdk: '>=2.18.6 <3.0.0'

dependencies:
  flutter:
    sdk: flutter

  # https://pub.dev/packages/easy_logger
  easy_logger: ^0.0.2

  # https://pub.dev/packages/path_provider
  # FFI, web version compatibility
  path_provider: ^1.6.14

  # https://pub.dev/packages/archive
  archive: 3.3.0
  # https://pub.dev/packages/http
  http: 0.13.5

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.1

flutter:
